---
- name: Authentik ldap server
  hosts: authentik-ldap
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: sshd

    - role: sudo

    - role: aide
      tags: security

    - role: prometheus_client
      tags: metrics

    - role: ca_client
      tags: auth

    - role: dnf
      tags: proxy,dnf

    - role: authentik_ldap
      tags: authentik_ldap,authentik-ldap,ldap
