---
authentik_packages:
  - podman
  - systemd-container
authentik_user: authie
authentik_db_image: "docker.io/library/postgres"
authentik_db_image_version: "18-alpine"
authentik_db_password: "{{ vault_authentik_db_password }}"
authentik_image: "ghcr.io/goauthentik/server"
authentik_image_version: "2026.5.6"
authentik_secret_key: "{{ vault_authentik_secret_key }}"
authentik_dirs:
  - /opt/authentik/data
  - /opt/authentik/custom-templates
  - /opt/authentik/certs
